[package]
name = "shock"
version = "0.2.0"
authors = ["VermillionAzure <VermillionAzure@users.noreply.github.com>"]
edition = "2018"

[dependencies]
uuid = { version = "0.7", features = ["serde", "v4"] }
libmath = "0.2.1"
nom = "4.2.0"
rustyline = "3.0.0"
